### ISSUE TITLE
Parent span IDs outside of application

### ISSUE THREAD

**Issue by xd009642** [jtescher/tracing-opentelemetry#7] opened 2020-01-13 10:30 UTC
So I tried to implement distributed tracing by decoding the span ID from the `grpc-trace-bin` header and got:

```
 grpc_service: Parent span string is "AAAtmbehJqGzkJk4E922WYKyAZn2DPyuJPmfAgE" and ID is 11094069011466746271
grpc_service_1    | thread 'main' panicked at 'tried to clone Id(11094069011466746271), but no span exists with that ID', 
```

Is there a way to create a span with the given ID to get around this error? Or a way this could be added to this crate

**Comment by jtescher** [comment] 2020-01-15 16:08
@xd009642  Is that the parent span id? There is work that needs to be done to assign the otel trace id to a `tracing` span.

The easiest currently is to extract the parent span context from headers, create an otel span with that span as the parent, assign that span as the current active span, and then create a `tracing` span after that which will properly have the parent set to the currently active span.

**Comment by xd009642** [comment] 2020-01-15 16:16
Yeah it's the otel span id. Eliza mentioned on discord there's some PRs being worked on to solve this issue so I was just planning on waiting and seeing what happens ☺️.

**Comment by xd009642** [comment] 2020-03-05 17:34
@jtescher just to revisit this, what part of the otel API would I use to create a span with that span as the parent? I did look at doing this but it wasn't evident how to achieve it

**Comment by jtescher** [comment] 2020-03-06 05:42
@xd009642 you can extract a span context from headers with the text extractor apis, e.g. for the b3 single header format:

```rust
// Header map can be anything that impls `api::Carrier`
let mut header_map: HashMap<&'static str, String> = HashMap::new();
header_map.insert("X-B3", "4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-1".to_string());

// Extract otel context from headers
let parent_context = api::B3Propagator::new(true).extract(&header_map);
let tracer = global::trace_provider().get_tracer("example");

// Create new app span with extracted context as parent to link them
let span = tracer.start("span_name", Some(parent_context));
```

**Comment by jtescher** [comment] 2020-03-06 05:44
@xd009642 I have a branch that has some ideas worked out [here](https://github.com/jtescher/tracing-opentelemetry/blob/feature/span-extension/examples/string_extractor.rs) if you want to see one possibility. It's really just waiting on the work in https://github.com/open-telemetry/opentelemetry-rust/pull/72 to settle.

**Comment by xd009642** [comment] 2020-03-06 08:19
Cool I'll be a bit more patient then :smile:

**Comment by xd009642** [comment] 2020-03-06 11:42
So for brevity I've gotten rid of imports and other initialisation etc but this is what my server is doing:

```Rust

fn tracing_init() {
    let builder = opentelemetry_jaeger::Exporter::builder()
        .with_agent_endpoint(url);
    
    let exporter = builder
        .with_process(opentelemetry_jaeger::Process {
            service_name: service_name,
            tags: vec![KeyValue::new("version", crate_version!())],
        })
        .init()?;

    let provider = sdk::Provider::builder()
        .with_simple_exporter(exporter)
        .with_config(sdk::Config {
            default_sampler: Box::new(Sampler::Always),
            ..Default::default()
        })
        .build();

    let tracer = provider.get_tracer("my-tracer");
    let opentelemetry = OpentelemetryLayer::with_tracer(tracer);

    let subscriber = filter
        .and_then(opentelemetry)
        .with_subscriber(Registry::default());

    tracing::subscriber::set_global_default(subscriber)?;
}

/// Run the server with the given config
pub async fn run() -> Result<(), Box<dyn std::error::Error>> {
    let service_inst = create_tonic_service_instance();

    Server::builder()
        .trace_fn(|header| {
            let parent = match header.get("grpc-trace-bin") {
                Some(parent) => {
                    if let Ok(bytes) = base64::decode(parent.as_bytes()) {
                        let bp = BinaryPropagator::new();
                        let span_state = bp.from_bytes(bytes);
                        Some(span_state)
                    } else {
                        None
                    }
                }
                None => None,
            };
            let tracer = global::trace_provider().get_tracer("my-tracer");
            let _span = tracer.start("request received", parent);
            info_span!("Received request")
        })
        .add_service(service)
        .await?;
    Ok(())
}


#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing_init();
    run().await?;
    Ok(())
}
```

It gets the parent IDs correctly from the request header, I've printed out the `span_state` variable in debug and all the information matches perfectly. But the spans between services still aren't linked and I can't get between them in the jaeger gui. Does anything stand out as immediately wrong to you?

**Comment by jtescher** [comment] 2020-03-06 23:22
So the issue is explicitly assigning `_span`'s context to be the parent of the result of `info_span!`. I think a temporary workaround in this case would be to explicitly assign the otel span to be active, which will then make it the parent of the otel span associated with `info_span` implicitly. This works in some conditions, e.g. it must happen _before_ the `tracing` root span is created among other things.

```rust
// hacky workaround
...
let span = tracer.start("request received", parent);
tracer.mark_span_as_active(&span);
info_span!("Received request")
...
```

This is all fixed in the work in progress branch though [set_parent_context](https://github.com/jtescher/tracing-opentelemetry/blob/feature/span-extension/src/layer.rs#L49) which will let you call something like:

```rust
// Simple assignment of parent context
...
let request_span = info_span!("Received request");
request_span.set_parent_context(parent)
...
```

And you won't have to worry about getting a tracer or creating an otel span 👍

**Comment by xd009642** [comment] 2020-03-09 14:53
I tried it and it didn't seem to work, I don't really have time to look into it though so when I get some time I'll try and investigate deeper

**Comment by jtescher** [comment] 2020-03-14 23:43
Yeah the issue with tonic's `trace_fn` is you would have to manually mark the current span as no longer active at some future time, which would be very easy to not get right or cause other issues in reporting. Best to wait for the next release which should be coming shortly.

**Comment by jtescher** [comment] 2020-03-15 00:37
I also created a tonic example in https://github.com/jtescher/tracing-opentelemetry/tree/feature/span-extension/examples/tonic to show how it could work once things are merged with a client and server, hope that helps

**Closed as completed** 2020-04-04 04:38 UTC
